// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Tokens Backend Service
//
//	Tokens WebSite Backend Service
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /
//	Version: development
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
