

services:
  tokens-dev:
    container_name: tokens-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ADDR=8000
      - LOG_LEVEL=DEBUG
      - MIGRATIONS_DIR=/migrations
      - POSTGRES_URI=postgres://postgres:tokens@postgres:5432/tokens_db?sslmode=disable
      - JWT_SIGNIN_KEY=MaximAdamov2002
      - ACCESS_TOKEN_TTL=15m
      - REFRESH_TOKEN_TTL=30m
      - REFRESH_TOKEN_LENGTH=32
    ports:
      - 8206:8000
    depends_on:
      - postgres
    networks:
      - tokens_network

  postgres:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5448:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=tokens_db
      - POSTGRES_PASSWORD=tokens
    networks:
      - tokens_network

volumes:
  postgres_data:
    driver: local

networks:
  tokens_network:
    driver: bridge