// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	models "github.com/Maksim646/tokens/internal/api/definition"
)

// GetTokensReader is a Reader for the GetTokens structure.
type GetTokensReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTokensReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTokensOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTokensBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTokensInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /auth/token] GetTokens", response, response.Code())
	}
}

// NewGetTokensOK creates a GetTokensOK with default headers values
func NewGetTokensOK() *GetTokensOK {
	return &GetTokensOK{}
}

/*
GetTokensOK describes a response with status code 200, with default header values.

Successful Tokens Response
*/
type GetTokensOK struct {
	Payload *models.Tokens
}

// IsSuccess returns true when this get tokens o k response has a 2xx status code
func (o *GetTokensOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get tokens o k response has a 3xx status code
func (o *GetTokensOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tokens o k response has a 4xx status code
func (o *GetTokensOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tokens o k response has a 5xx status code
func (o *GetTokensOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get tokens o k response a status code equal to that given
func (o *GetTokensOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get tokens o k response
func (o *GetTokensOK) Code() int {
	return 200
}

func (o *GetTokensOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/token][%d] getTokensOK %s", 200, payload)
}

func (o *GetTokensOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/token][%d] getTokensOK %s", 200, payload)
}

func (o *GetTokensOK) GetPayload() *models.Tokens {
	return o.Payload
}

func (o *GetTokensOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Tokens)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokensBadRequest creates a GetTokensBadRequest with default headers values
func NewGetTokensBadRequest() *GetTokensBadRequest {
	return &GetTokensBadRequest{}
}

/*
GetTokensBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type GetTokensBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this get tokens bad request response has a 2xx status code
func (o *GetTokensBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tokens bad request response has a 3xx status code
func (o *GetTokensBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tokens bad request response has a 4xx status code
func (o *GetTokensBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get tokens bad request response has a 5xx status code
func (o *GetTokensBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get tokens bad request response a status code equal to that given
func (o *GetTokensBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get tokens bad request response
func (o *GetTokensBadRequest) Code() int {
	return 400
}

func (o *GetTokensBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/token][%d] getTokensBadRequest %s", 400, payload)
}

func (o *GetTokensBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/token][%d] getTokensBadRequest %s", 400, payload)
}

func (o *GetTokensBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTokensBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTokensInternalServerError creates a GetTokensInternalServerError with default headers values
func NewGetTokensInternalServerError() *GetTokensInternalServerError {
	return &GetTokensInternalServerError{}
}

/*
GetTokensInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type GetTokensInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this get tokens internal server error response has a 2xx status code
func (o *GetTokensInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get tokens internal server error response has a 3xx status code
func (o *GetTokensInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get tokens internal server error response has a 4xx status code
func (o *GetTokensInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get tokens internal server error response has a 5xx status code
func (o *GetTokensInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get tokens internal server error response a status code equal to that given
func (o *GetTokensInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get tokens internal server error response
func (o *GetTokensInternalServerError) Code() int {
	return 500
}

func (o *GetTokensInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/token][%d] getTokensInternalServerError %s", 500, payload)
}

func (o *GetTokensInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /auth/token][%d] getTokensInternalServerError %s", 500, payload)
}

func (o *GetTokensInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetTokensInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
