// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthTokenParams creates a new GetAuthTokenParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthTokenParams() *GetAuthTokenParams {
	return &GetAuthTokenParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthTokenParamsWithTimeout creates a new GetAuthTokenParams object
// with the ability to set a timeout on a request.
func NewGetAuthTokenParamsWithTimeout(timeout time.Duration) *GetAuthTokenParams {
	return &GetAuthTokenParams{
		timeout: timeout,
	}
}

// NewGetAuthTokenParamsWithContext creates a new GetAuthTokenParams object
// with the ability to set a context for a request.
func NewGetAuthTokenParamsWithContext(ctx context.Context) *GetAuthTokenParams {
	return &GetAuthTokenParams{
		Context: ctx,
	}
}

// NewGetAuthTokenParamsWithHTTPClient creates a new GetAuthTokenParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthTokenParamsWithHTTPClient(client *http.Client) *GetAuthTokenParams {
	return &GetAuthTokenParams{
		HTTPClient: client,
	}
}

/*
GetAuthTokenParams contains all the parameters to send to the API endpoint

	for the get auth token operation.

	Typically these are written to a http.Request.
*/
type GetAuthTokenParams struct {

	/* UserID.

	   GUID
	*/
	UserID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get auth token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthTokenParams) WithDefaults() *GetAuthTokenParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get auth token params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthTokenParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get auth token params
func (o *GetAuthTokenParams) WithTimeout(timeout time.Duration) *GetAuthTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get auth token params
func (o *GetAuthTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get auth token params
func (o *GetAuthTokenParams) WithContext(ctx context.Context) *GetAuthTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get auth token params
func (o *GetAuthTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get auth token params
func (o *GetAuthTokenParams) WithHTTPClient(client *http.Client) *GetAuthTokenParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get auth token params
func (o *GetAuthTokenParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithUserID adds the userID to the get auth token params
func (o *GetAuthTokenParams) WithUserID(userID string) *GetAuthTokenParams {
	o.SetUserID(userID)
	return o
}

// SetUserID adds the userId to the get auth token params
func (o *GetAuthTokenParams) SetUserID(userID string) {
	o.UserID = userID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// query param user_id
	qrUserID := o.UserID
	qUserID := qrUserID
	if qUserID != "" {

		if err := r.SetQueryParam("user_id", qUserID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
