// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/tokens/internal/api/definition"
)

// GetTokensOKCode is the HTTP code returned for type GetTokensOK
const GetTokensOKCode int = 200

/*
GetTokensOK Successful Tokens Response

swagger:response getTokensOK
*/
type GetTokensOK struct {

	/*
	  In: Body
	*/
	Payload *models.Tokens `json:"body,omitempty"`
}

// NewGetTokensOK creates GetTokensOK with default headers values
func NewGetTokensOK() *GetTokensOK {

	return &GetTokensOK{}
}

// WithPayload adds the payload to the get tokens o k response
func (o *GetTokensOK) WithPayload(payload *models.Tokens) *GetTokensOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tokens o k response
func (o *GetTokensOK) SetPayload(payload *models.Tokens) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokensOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTokensBadRequestCode is the HTTP code returned for type GetTokensBadRequest
const GetTokensBadRequestCode int = 400

/*
GetTokensBadRequest Bad request

swagger:response getTokensBadRequest
*/
type GetTokensBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTokensBadRequest creates GetTokensBadRequest with default headers values
func NewGetTokensBadRequest() *GetTokensBadRequest {

	return &GetTokensBadRequest{}
}

// WithPayload adds the payload to the get tokens bad request response
func (o *GetTokensBadRequest) WithPayload(payload *models.Error) *GetTokensBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tokens bad request response
func (o *GetTokensBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokensBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetTokensInternalServerErrorCode is the HTTP code returned for type GetTokensInternalServerError
const GetTokensInternalServerErrorCode int = 500

/*
GetTokensInternalServerError Internal server error

swagger:response getTokensInternalServerError
*/
type GetTokensInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTokensInternalServerError creates GetTokensInternalServerError with default headers values
func NewGetTokensInternalServerError() *GetTokensInternalServerError {

	return &GetTokensInternalServerError{}
}

// WithPayload adds the payload to the get tokens internal server error response
func (o *GetTokensInternalServerError) WithPayload(payload *models.Error) *GetTokensInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tokens internal server error response
func (o *GetTokensInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTokensInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
