// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTokensHandlerFunc turns a function with the right signature into a get tokens handler
type GetTokensHandlerFunc func(GetTokensParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTokensHandlerFunc) Handle(params GetTokensParams) middleware.Responder {
	return fn(params)
}

// GetTokensHandler interface for that can handle valid get tokens params
type GetTokensHandler interface {
	Handle(GetTokensParams) middleware.Responder
}

// NewGetTokens creates a new http.Handler for the get tokens operation
func NewGetTokens(ctx *middleware.Context, handler GetTokensHandler) *GetTokens {
	return &GetTokens{Context: ctx, Handler: handler}
}

/*
	GetTokens swagger:route GET /auth/token getTokens

# Get access and refresh tokens

Get access and refresh tokens by GUID
*/
type GetTokens struct {
	Context *middleware.Context
	Handler GetTokensHandler
}

func (o *GetTokens) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTokensParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
