// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Maksim646/Tokens/internal/api/definition"
)

// GetAuthTokenOKCode is the HTTP code returned for type GetAuthTokenOK
const GetAuthTokenOKCode int = 200

/*
GetAuthTokenOK Successful Tokens Response

swagger:response getAuthTokenOK
*/
type GetAuthTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.TokensResponse `json:"body,omitempty"`
}

// NewGetAuthTokenOK creates GetAuthTokenOK with default headers values
func NewGetAuthTokenOK() *GetAuthTokenOK {

	return &GetAuthTokenOK{}
}

// WithPayload adds the payload to the get auth token o k response
func (o *GetAuthTokenOK) WithPayload(payload *models.TokensResponse) *GetAuthTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth token o k response
func (o *GetAuthTokenOK) SetPayload(payload *models.TokensResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuthTokenBadRequestCode is the HTTP code returned for type GetAuthTokenBadRequest
const GetAuthTokenBadRequestCode int = 400

/*
GetAuthTokenBadRequest Bad request

swagger:response getAuthTokenBadRequest
*/
type GetAuthTokenBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthTokenBadRequest creates GetAuthTokenBadRequest with default headers values
func NewGetAuthTokenBadRequest() *GetAuthTokenBadRequest {

	return &GetAuthTokenBadRequest{}
}

// WithPayload adds the payload to the get auth token bad request response
func (o *GetAuthTokenBadRequest) WithPayload(payload *models.Error) *GetAuthTokenBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth token bad request response
func (o *GetAuthTokenBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthTokenBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuthTokenInternalServerErrorCode is the HTTP code returned for type GetAuthTokenInternalServerError
const GetAuthTokenInternalServerErrorCode int = 500

/*
GetAuthTokenInternalServerError Internal server error

swagger:response getAuthTokenInternalServerError
*/
type GetAuthTokenInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuthTokenInternalServerError creates GetAuthTokenInternalServerError with default headers values
func NewGetAuthTokenInternalServerError() *GetAuthTokenInternalServerError {

	return &GetAuthTokenInternalServerError{}
}

// WithPayload adds the payload to the get auth token internal server error response
func (o *GetAuthTokenInternalServerError) WithPayload(payload *models.Error) *GetAuthTokenInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get auth token internal server error response
func (o *GetAuthTokenInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthTokenInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
