// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"

	models "github.com/Maksim646/Tokens/internal/api/definition"
)

// PostAuthRefreshHandlerFunc turns a function with the right signature into a post auth refresh handler
type PostAuthRefreshHandlerFunc func(PostAuthRefreshParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuthRefreshHandlerFunc) Handle(params PostAuthRefreshParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// PostAuthRefreshHandler interface for that can handle valid post auth refresh params
type PostAuthRefreshHandler interface {
	Handle(PostAuthRefreshParams, *models.Principal) middleware.Responder
}

// NewPostAuthRefresh creates a new http.Handler for the post auth refresh operation
func NewPostAuthRefresh(ctx *middleware.Context, handler PostAuthRefreshHandler) *PostAuthRefresh {
	return &PostAuthRefresh{Context: ctx, Handler: handler}
}

/*
	PostAuthRefresh swagger:route POST /auth/refresh postAuthRefresh

# Update access and refresh tokens

New tokens by active refresh token
*/
type PostAuthRefresh struct {
	Context *middleware.Context
	Handler PostAuthRefreshHandler
}

func (o *PostAuthRefresh) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuthRefreshParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
