// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	models "github.com/Maksim646/tokens/internal/api/definition"
)

// NewPostAuthRefreshParams creates a new PostAuthRefreshParams object
//
// There are no default values defined in the spec.
func NewPostAuthRefreshParams() PostAuthRefreshParams {

	return PostAuthRefreshParams{}
}

// PostAuthRefreshParams contains all the bound params for the post auth refresh operation
// typically these are obtained from a http.Request
//
// swagger:parameters PostAuthRefresh
type PostAuthRefreshParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Refresh Token Body
	  Required: true
	  In: body
	*/
	RefreshTokenBody *models.RefreshTokenBody
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewPostAuthRefreshParams() beforehand.
func (o *PostAuthRefreshParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.RefreshTokenBody
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("refreshTokenBody", "body", ""))
			} else {
				res = append(res, errors.NewParseError("refreshTokenBody", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.RefreshTokenBody = &body
			}
		}
	} else {
		res = append(res, errors.Required("refreshTokenBody", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
