// Code generated by go-swagger; DO NOT EDIT.

package api

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/validate"

	models "github.com/Maksim646/tokens/internal/api/definition"
)

// NewRefreshTokensParams creates a new RefreshTokensParams object
//
// There are no default values defined in the spec.
func NewRefreshTokensParams() RefreshTokensParams {

	return RefreshTokensParams{}
}

// RefreshTokensParams contains all the bound params for the refresh tokens operation
// typically these are obtained from a http.Request
//
// swagger:parameters RefreshTokens
type RefreshTokensParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Refresh Token Body
	  Required: true
	  In: body
	*/
	Tokens *models.Tokens
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewRefreshTokensParams() beforehand.
func (o *RefreshTokensParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Tokens
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("tokens", "body", ""))
			} else {
				res = append(res, errors.NewParseError("tokens", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			ctx := validate.WithOperationRequest(r.Context())
			if err := body.ContextValidate(ctx, route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Tokens = &body
			}
		}
	} else {
		res = append(res, errors.Required("tokens", "body", ""))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
